/*
 * Copyright (c) 2019, The Linux Foundation. All rights reserved.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

///////////////////////////////////////////////////////////////////////////////////////////////
//
///////////////////////////////////////////////////////////////////////////////////////////////
//
// wcss_seq_hwiobase.h : automatically generated by Autoseq  3.8 3/6/2019 
// User Name:pbechana
//
// !! WARNING !!  DO NOT MANUALLY EDIT THIS FILE.
//
///////////////////////////////////////////////////////////////////////////////////////////////

#ifndef __WCSS_SEQ_BASE_H__
#define __WCSS_SEQ_BASE_H__

#ifdef SCALE_INCLUDES
	#include "HALhwio.h"
#else
	#include "msmhwio.h"
#endif

#include "rfa_from_wsi_seq_hwiobase.h"
#include "wcss_seq_hwiobase_ext.h"
#define SOC_WCSS_BASE_ADDR 0x00000000
///////////////////////////////////////////////////////////////////////////////////////////////
// Instance Relative Offsets from Block wcss
///////////////////////////////////////////////////////////////////////////////////////////////

#define SEQ_WCSS_ECAHB_OFFSET                                        0x00008400
#define SEQ_WCSS_ECAHB_TSLV_OFFSET                                   0x00009000
#define SEQ_WCSS_UMAC_NOC_OFFSET                                     0x00140000
#define SEQ_WCSS_PHYA_OFFSET                                         0x00300000
#define SEQ_WCSS_PHYA_WFAX_PCSS_PDMEM_REG_MAP_OFFSET                 0x00300000
#define SEQ_WCSS_PHYA_WFAX_PCSS_REG_MAP_OFFSET                       0x00380000
#define SEQ_WCSS_PHYA_WFAX_PCSS_DMAC0_REG_MAP_OFFSET                 0x00380400
#define SEQ_WCSS_PHYA_WFAX_PCSS_DMAC1_REG_MAP_OFFSET                 0x00380800
#define SEQ_WCSS_PHYA_WFAX_PCSS_DMAC2_REG_MAP_OFFSET                 0x00380c00
#define SEQ_WCSS_PHYA_WFAX_PCSS_DMAC3_REG_MAP_OFFSET                 0x00381000
#define SEQ_WCSS_PHYA_WFAX_PCSS_DMAC4_REG_MAP_OFFSET                 0x00381400
#define SEQ_WCSS_PHYA_WFAX_PCSS_DUAL_TIMER0_REG_MAP_OFFSET           0x00381800
#define SEQ_WCSS_PHYA_WFAX_PCSS_WATCHDOG_REG_MAP_OFFSET              0x00381c00
#define SEQ_WCSS_PHYA_WFAX_PCSS_DMAC5_REG_MAP_OFFSET                 0x00382c00
#define SEQ_WCSS_PHYA_WFAX_PCSS_DMAC6_REG_MAP_OFFSET                 0x00383000
#define SEQ_WCSS_PHYA_WFAX_PCSS_DUAL_TIMER1_REG_MAP_OFFSET           0x00383400
#define SEQ_WCSS_PHYA_WFAX_NOC_REG_MAP_OFFSET                        0x00388000
#define SEQ_WCSS_PHYA_WFAX_TXFD_REG_MAP_OFFSET                       0x00390000
#define SEQ_WCSS_PHYA_WFAX_RXTD_REG_MAP_OFFSET                       0x003a0000
#define SEQ_WCSS_PHYA_WFAX_TXTD_REG_MAP_OFFSET                       0x003b0000
#define SEQ_WCSS_PHYA_WFAX_TXBF_REG_MAP_OFFSET                       0x003c0000
#define SEQ_WCSS_PHYA_WFAX_DEMFRONT_0_REG_MAP_OFFSET                 0x00400000
#define SEQ_WCSS_PHYA_WFAX_PHYRF_REG_MAP_OFFSET                      0x00480000
#define SEQ_WCSS_PHYA_WFAX_ROBE_REG_MAP_OFFSET                       0x004b0000
#define SEQ_WCSS_PHYA_WFAX_DEMFRONT_1_REG_MAP_OFFSET                 0x00500000
#define SEQ_WCSS_UMAC_OFFSET                                         0x00a00000
#define SEQ_WCSS_UMAC_CXC_TOP_REG_OFFSET                             0x00a20000
#define SEQ_WCSS_UMAC_CXC_TOP_REG_CXC_BMH_REG_OFFSET                 0x00a20000
#define SEQ_WCSS_UMAC_CXC_TOP_REG_CXC_LCMH_REG_OFFSET                0x00a22000
#define SEQ_WCSS_UMAC_CXC_TOP_REG_CXC_MCIBASIC_REG_OFFSET            0x00a24000
#define SEQ_WCSS_UMAC_CXC_TOP_REG_CXC_LMH_REG_OFFSET                 0x00a26000
#define SEQ_WCSS_UMAC_CXC_TOP_REG_CXC_SMH_REG_OFFSET                 0x00a28000
#define SEQ_WCSS_UMAC_CXC_TOP_REG_CXC_PMH_REG_OFFSET                 0x00a2a000
#define SEQ_WCSS_UMAC_MAC_TRACER_REG_OFFSET                          0x00a30000
#define SEQ_WCSS_UMAC_WBM_REG_OFFSET                                 0x00a34000
#define SEQ_WCSS_UMAC_REO_REG_OFFSET                                 0x00a38000
#define SEQ_WCSS_UMAC_TQM_REG_OFFSET                                 0x00a3c000
#define SEQ_WCSS_UMAC_MAC_UMCMN_REG_OFFSET                           0x00a40000
#define SEQ_WCSS_UMAC_MAC_TCL_REG_OFFSET                             0x00a44000
#define SEQ_WCSS_UMAC_MAC_CMN_PARSER_REG_OFFSET                      0x00a47000
#define SEQ_WCSS_UMAC_MAC_CCE_TCL_REG_OFFSET                         0x00a4a000
#define SEQ_WCSS_WMAC0_OFFSET                                        0x00a80000
#define SEQ_WCSS_WMAC0_MAC_PDG_REG_OFFSET                            0x00a80000
#define SEQ_WCSS_WMAC0_MAC_TXDMA_REG_OFFSET                          0x00a83000
#define SEQ_WCSS_WMAC0_MAC_RXDMA_REG_OFFSET                          0x00a86000
#define SEQ_WCSS_WMAC0_MAC_MCMN_REG_OFFSET                           0x00a89000
#define SEQ_WCSS_WMAC0_MAC_RXPCU_REG_OFFSET                          0x00a8c000
#define SEQ_WCSS_WMAC0_MAC_TXPCU_REG_OFFSET                          0x00a8f000
#define SEQ_WCSS_WMAC0_MAC_AMPI_REG_OFFSET                           0x00a92000
#define SEQ_WCSS_WMAC0_MAC_RXOLE_REG_OFFSET                          0x00a95000
#define SEQ_WCSS_WMAC0_MAC_RXOLE_PARSER_REG_OFFSET                   0x00a98000
#define SEQ_WCSS_WMAC0_MAC_CCE_REG_OFFSET                            0x00a9b000
#define SEQ_WCSS_WMAC0_MAC_TXOLE_REG_OFFSET                          0x00a9e000
#define SEQ_WCSS_WMAC0_MAC_TXOLE_PARSER_REG_OFFSET                   0x00aa1000
#define SEQ_WCSS_WMAC0_MAC_RRI_REG_OFFSET                            0x00aa4000
#define SEQ_WCSS_WMAC0_MAC_CRYPTO_REG_OFFSET                         0x00aa7000
#define SEQ_WCSS_WMAC0_MAC_HWSCH_REG_OFFSET                          0x00aaa000
#define SEQ_WCSS_WMAC0_MAC_MXI_REG_OFFSET                            0x00ab0000
#define SEQ_WCSS_WMAC0_MAC_SFM_REG_OFFSET                            0x00ab3000
#define SEQ_WCSS_WMAC0_MAC_RXDMA1_REG_OFFSET                         0x00ab6000
#define SEQ_WCSS_APB_TSLV_OFFSET                                     0x00b40000
#define SEQ_WCSS_TOP_CMN_OFFSET                                      0x00b50000
#define SEQ_WCSS_WCMN_CORE_OFFSET                                    0x00b58000
#define SEQ_WCSS_WFSS_PMM_OFFSET                                     0x00b60000
#define SEQ_WCSS_PMM_TOP_OFFSET                                      0x00b70000
#define SEQ_WCSS_WL_MSIP_OFFSET                                      0x00b80000
#define SEQ_WCSS_WL_MSIP_RBIST_TX_CH0_OFFSET                         0x00b80000
#define SEQ_WCSS_WL_MSIP_WL_DAC_CH0_OFFSET                           0x00b80180
#define SEQ_WCSS_WL_MSIP_WL_DAC_DIG_CORRECTION_CH0_OFFSET            0x00b801c0
#define SEQ_WCSS_WL_MSIP_WL_DAC_MISC_CH0_OFFSET                      0x00b802c0
#define SEQ_WCSS_WL_MSIP_WL_DAC_BBCLKGEN_CH0_OFFSET                  0x00b8033c
#define SEQ_WCSS_WL_MSIP_WL_ADC_CH0_OFFSET                           0x00b80340
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_I_EVEN_CH0_OFFSET           0x00b80400
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_I_ODD_CH0_OFFSET            0x00b80440
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_Q_EVEN_CH0_OFFSET           0x00b80480
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_Q_ODD_CH0_OFFSET            0x00b804c0
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_RO_CH0_OFFSET               0x00b80500
#define SEQ_WCSS_WL_MSIP_WL_ADC_BBCLKGEN_CH0_OFFSET                  0x00b8059c
#define SEQ_WCSS_WL_MSIP_RBIST_TX_CH1_OFFSET                         0x00b81000
#define SEQ_WCSS_WL_MSIP_WL_DAC_CH1_OFFSET                           0x00b81180
#define SEQ_WCSS_WL_MSIP_WL_DAC_DIG_CORRECTION_CH1_OFFSET            0x00b811c0
#define SEQ_WCSS_WL_MSIP_WL_DAC_MISC_CH1_OFFSET                      0x00b812c0
#define SEQ_WCSS_WL_MSIP_WL_DAC_BBCLKGEN_CH1_OFFSET                  0x00b8133c
#define SEQ_WCSS_WL_MSIP_WL_ADC_CH1_OFFSET                           0x00b81340
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_I_EVEN_CH1_OFFSET           0x00b81400
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_I_ODD_CH1_OFFSET            0x00b81440
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_Q_EVEN_CH1_OFFSET           0x00b81480
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_Q_ODD_CH1_OFFSET            0x00b814c0
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_RO_CH1_OFFSET               0x00b81500
#define SEQ_WCSS_WL_MSIP_WL_ADC_BBCLKGEN_CH1_OFFSET                  0x00b8159c
#define SEQ_WCSS_WL_MSIP_RBIST_TX_CH2_OFFSET                         0x00b82000
#define SEQ_WCSS_WL_MSIP_WL_DAC_CH2_OFFSET                           0x00b82180
#define SEQ_WCSS_WL_MSIP_WL_DAC_DIG_CORRECTION_CH2_OFFSET            0x00b821c0
#define SEQ_WCSS_WL_MSIP_WL_DAC_MISC_CH2_OFFSET                      0x00b822c0
#define SEQ_WCSS_WL_MSIP_WL_DAC_BBCLKGEN_CH2_OFFSET                  0x00b8233c
#define SEQ_WCSS_WL_MSIP_WL_ADC_CH2_OFFSET                           0x00b82340
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_I_EVEN_CH2_OFFSET           0x00b82400
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_I_ODD_CH2_OFFSET            0x00b82440
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_Q_EVEN_CH2_OFFSET           0x00b82480
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_Q_ODD_CH2_OFFSET            0x00b824c0
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_RO_CH2_OFFSET               0x00b82500
#define SEQ_WCSS_WL_MSIP_WL_ADC_BBCLKGEN_CH2_OFFSET                  0x00b8259c
#define SEQ_WCSS_WL_MSIP_RBIST_TX_CH3_OFFSET                         0x00b83000
#define SEQ_WCSS_WL_MSIP_WL_DAC_CH3_OFFSET                           0x00b83180
#define SEQ_WCSS_WL_MSIP_WL_DAC_DIG_CORRECTION_CH3_OFFSET            0x00b831c0
#define SEQ_WCSS_WL_MSIP_WL_DAC_MISC_CH3_OFFSET                      0x00b832c0
#define SEQ_WCSS_WL_MSIP_WL_DAC_BBCLKGEN_CH3_OFFSET                  0x00b8333c
#define SEQ_WCSS_WL_MSIP_WL_ADC_CH3_OFFSET                           0x00b83340
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_I_EVEN_CH3_OFFSET           0x00b83400
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_I_ODD_CH3_OFFSET            0x00b83440
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_Q_EVEN_CH3_OFFSET           0x00b83480
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_Q_ODD_CH3_OFFSET            0x00b834c0
#define SEQ_WCSS_WL_MSIP_WL_ADC_POSTPROC_RO_CH3_OFFSET               0x00b83500
#define SEQ_WCSS_WL_MSIP_WL_ADC_BBCLKGEN_CH3_OFFSET                  0x00b8359c
#define SEQ_WCSS_WL_MSIP_MSIP_TMUX_OFFSET                            0x00b8d000
#define SEQ_WCSS_WL_MSIP_MSIP_OTP_OFFSET                             0x00b8d080
#define SEQ_WCSS_WL_MSIP_MSIP_LDO_CTRL_OFFSET                        0x00b8d0a0
#define SEQ_WCSS_WL_MSIP_WL_ICIC_OFFSET                              0x00b8d340
#define SEQ_WCSS_WL_MSIP_WL_ICIC_POSTPROC_I_EVEN_OFFSET              0x00b8d400
#define SEQ_WCSS_WL_MSIP_WL_ICIC_POSTPROC_I_ODD_OFFSET               0x00b8d440
#define SEQ_WCSS_WL_MSIP_WL_ICIC_POSTPROC_Q_EVEN_OFFSET              0x00b8d480
#define SEQ_WCSS_WL_MSIP_WL_ICIC_POSTPROC_Q_ODD_OFFSET               0x00b8d4c0
#define SEQ_WCSS_WL_MSIP_WL_ICIC_POSTPROC_RO_OFFSET                  0x00b8d500
#define SEQ_WCSS_WL_MSIP_WL_ICIC_BBCLKGEN_OFFSET                     0x00b8d59c
#define SEQ_WCSS_WL_MSIP_MSIP_BIAS_OFFSET                            0x00b8e000
#define SEQ_WCSS_WL_MSIP_BBPLL_OFFSET                                0x00b8f000
#define SEQ_WCSS_WL_MSIP_WL_TOP_CLKGEN_OFFSET                        0x00b8f800
#define SEQ_WCSS_WL_MSIP_MSIP_DRM_REG_OFFSET                         0x00b8fc00
#define SEQ_WCSS_DBG_OFFSET                                          0x00b90000
#define SEQ_WCSS_DBG_WCSS_DBG_DAPROM_OFFSET                          0x00b90000
#define SEQ_WCSS_DBG_CSR_WCSS_DBG_CSR_OFFSET                         0x00b91000
#define SEQ_WCSS_DBG_TSGEN_CXTSGEN_OFFSET                            0x00b92000
#define SEQ_WCSS_DBG_CTIDBG_QC_CTI_32T_8CH_OFFSET                    0x00b94000
#define SEQ_WCSS_DBG_CTINOC_QC_CTI_8T_8CH_OFFSET                     0x00b95000
#define SEQ_WCSS_DBG_CTIIRQ_QC_CTI_32T_8CH_OFFSET                    0x00b96000
#define SEQ_WCSS_DBG_WCSS_DBG_TSTMP_INJCTR_OFFSET                    0x00ba0000
#define SEQ_WCSS_DBG_TPDM_OFFSET                                     0x00ba1000
#define SEQ_WCSS_DBG_TPDM_TPDM_ATB64_CMB40_DSB256_CSBE6C04F7_SUB_OFFSET 0x00ba1280
#define SEQ_WCSS_DBG_TPDM_TPDM_ATB64_CMB40_DSB256_CSBE6C04F7_GPR_OFFSET 0x00ba1000
#define SEQ_WCSS_DBG_TPDA_OFFSET                                     0x00ba2000
#define SEQ_WCSS_DBG_CXATBFUNNEL_128W8SP_OFFSET                      0x00ba3000
#define SEQ_WCSS_DBG_TMC_CXTMC_F128W32K_OFFSET                       0x00ba4000
#define SEQ_WCSS_DBG_OUTFUN_CXATBFUNNEL_128W2SP_OFFSET               0x00ba6000
#define SEQ_WCSS_DBG_OUTDMUX_ATB_DEMUX_OFFSET                        0x00ba8000
#define SEQ_WCSS_DBG_TRCCNTRS_OFFSET                                 0x00ba9000
#define SEQ_WCSS_DBG_UNOC_UMAC_NOC_OFFSET                            0x00bb0000
#define SEQ_WCSS_DBG_PHYA_PHYA_DBG_OFFSET                            0x00bc0000
#define SEQ_WCSS_DBG_PHYA_PHYA_DBG_PHYA_NOC_OFFSET                   0x00bc0000
#define SEQ_WCSS_DBG_PHYA_PHYA_DBG_FUN_CXATBFUNNEL_64W8SP_OFFSET     0x00bc4000
#define SEQ_WCSS_DBG_PHYA_PHYA_DBG_CTI_QC_CTI_10T_8CH_OFFSET         0x00bc5000
#define SEQ_WCSS_DBG_PHYA_PHYA_DBG_TRC_PHYTRC_CTRL_OFFSET            0x00bc6000
#define SEQ_WCSS_DBG_PHYA_PHYA_DBG_ITM_OFFSET                        0x00bc8000
#define SEQ_WCSS_DBG_PHYA_PHYA_DBG_DWT_OFFSET                        0x00bc9000
#define SEQ_WCSS_DBG_PHYA_PHYA_DBG_FPB_OFFSET                        0x00bca000
#define SEQ_WCSS_DBG_PHYA_PHYA_DBG_SCS_OFFSET                        0x00bcb000
#define SEQ_WCSS_DBG_PHYA_PHYA_DBG_M3_ETM_OFFSET                     0x00bcc000
#define SEQ_WCSS_DBG_PHYA_PHYA_DBG_M3CTI_QC_CTI_8T_8CH_OFFSET        0x00bcd000
#define SEQ_WCSS_DBG_PHYA_PHYA_DBG_CPU0_M3_AHB_AP_OFFSET             0x00bce000
#define SEQ_WCSS_DBG_BUS_TIMEOUT_OFFSET                              0x00c01000
#define SEQ_WCSS_RET_AHB_OFFSET                                      0x00c90000
#define SEQ_WCSS_WAHB_TSLV_OFFSET                                    0x00ca0000
#define SEQ_WCSS_CC_OFFSET                                           0x00cb0000
#define SEQ_WCSS_UMAC_ACMT_OFFSET                                    0x00cc0000

#define SEQ_WCSS_Q6SS_WLAN_OFFSET                                    0x00d00000
#define SEQ_WCSS_Q6SS_WLAN_QDSP6V67SS_OFFSET                         0x00d00000
#define SEQ_WCSS_Q6SS_WLAN_QDSP6V67SS_QDSP6V67SS_PUBLIC_OFFSET       0x00d00000
#define SEQ_WCSS_Q6SS_WLAN_QDSP6V67SS_QDSP6V67SS_PUBLIC_QDSP6V67SS_PUB_OFFSET 0x00d00000
#define SEQ_WCSS_Q6SS_WLAN_QDSP6V67SS_QDSP6V67SS_PRIVATE_OFFSET      0x00d80000
#define SEQ_WCSS_Q6SS_WLAN_QDSP6V67SS_QDSP6V67SS_PRIVATE_QDSP6V67SS_CSR_OFFSET 0x00d80000
#define SEQ_WCSS_Q6SS_WLAN_QDSP6V67SS_QDSP6V67SS_PRIVATE_QDSP6V67SS_L2VIC_OFFSET 0x00d90000
#define SEQ_WCSS_Q6SS_WLAN_QDSP6V67SS_QDSP6V67SS_PRIVATE_QDSP6SS_QTMR_AC_OFFSET 0x00da0000
#define SEQ_WCSS_Q6SS_WLAN_QDSP6V67SS_QDSP6V67SS_PRIVATE_QTMR_F0_OFFSET 0x00da1000
#define SEQ_WCSS_Q6SS_WLAN_QDSP6V67SS_QDSP6V67SS_PRIVATE_QTMR_F1_OFFSET 0x00da2000
#define SEQ_WCSS_Q6SS_WLAN_QDSP6V67SS_QDSP6V67SS_PRIVATE_QTMR_F2_OFFSET 0x00da3000
#define SEQ_WCSS_Q6SS_WLAN_QDSP6V67SS_QDSP6V67SS_PRIVATE_QDSP6V67SS_RSCC_OFFSET 0x00db0000
#define SEQ_WCSS_Q6SS_WLAN_QDSP6V67SS_QDSP6V67SS_PRIVATE_QDSP6V67SS_RSCC_RSCC_RSC_OFFSET 0x00db0000

///////////////////////////////////////////////////////////////////////////////////////////////
// Instance Relative Offsets from Block wfax_top
///////////////////////////////////////////////////////////////////////////////////////////////

#define SEQ_WFAX_TOP_WFAX_PCSS_PDMEM_REG_MAP_OFFSET                  0x00000000
#define SEQ_WFAX_TOP_WFAX_PCSS_REG_MAP_OFFSET                        0x00080000
#define SEQ_WFAX_TOP_WFAX_PCSS_DMAC0_REG_MAP_OFFSET                  0x00080400
#define SEQ_WFAX_TOP_WFAX_PCSS_DMAC1_REG_MAP_OFFSET                  0x00080800
#define SEQ_WFAX_TOP_WFAX_PCSS_DMAC2_REG_MAP_OFFSET                  0x00080c00
#define SEQ_WFAX_TOP_WFAX_PCSS_DMAC3_REG_MAP_OFFSET                  0x00081000
#define SEQ_WFAX_TOP_WFAX_PCSS_DMAC4_REG_MAP_OFFSET                  0x00081400
#define SEQ_WFAX_TOP_WFAX_PCSS_DUAL_TIMER0_REG_MAP_OFFSET            0x00081800
#define SEQ_WFAX_TOP_WFAX_PCSS_WATCHDOG_REG_MAP_OFFSET               0x00081c00
#define SEQ_WFAX_TOP_WFAX_PCSS_DMAC5_REG_MAP_OFFSET                  0x00082c00
#define SEQ_WFAX_TOP_WFAX_PCSS_DMAC6_REG_MAP_OFFSET                  0x00083000
#define SEQ_WFAX_TOP_WFAX_PCSS_DUAL_TIMER1_REG_MAP_OFFSET            0x00083400
#define SEQ_WFAX_TOP_WFAX_NOC_REG_MAP_OFFSET                         0x00088000
#define SEQ_WFAX_TOP_WFAX_TXFD_REG_MAP_OFFSET                        0x00090000
#define SEQ_WFAX_TOP_WFAX_RXTD_REG_MAP_OFFSET                        0x000a0000
#define SEQ_WFAX_TOP_WFAX_TXTD_REG_MAP_OFFSET                        0x000b0000
#define SEQ_WFAX_TOP_WFAX_TXBF_REG_MAP_OFFSET                        0x000c0000
#define SEQ_WFAX_TOP_WFAX_DEMFRONT_0_REG_MAP_OFFSET                  0x00100000
#define SEQ_WFAX_TOP_WFAX_PHYRF_REG_MAP_OFFSET                       0x00180000
#define SEQ_WFAX_TOP_WFAX_ROBE_REG_MAP_OFFSET                        0x001b0000
#define SEQ_WFAX_TOP_WFAX_DEMFRONT_1_REG_MAP_OFFSET                  0x00200000
#define SEQ_WFAX_TOP_RFA_REG_MAP_OFFSET                              0x002c0000
#define SEQ_WFAX_TOP_WFAX_IRON2G_REG_MAP_OFFSET                      SEQ_WFAX_TOP_RFA_REG_MAP_OFFSET


///////////////////////////////////////////////////////////////////////////////////////////////
// Instance Relative Offsets from Block umac_top_reg
///////////////////////////////////////////////////////////////////////////////////////////////

#define SEQ_UMAC_TOP_REG_CXC_TOP_REG_OFFSET                          0x00020000
#define SEQ_UMAC_TOP_REG_CXC_TOP_REG_CXC_BMH_REG_OFFSET              0x00020000
#define SEQ_UMAC_TOP_REG_CXC_TOP_REG_CXC_LCMH_REG_OFFSET             0x00022000
#define SEQ_UMAC_TOP_REG_CXC_TOP_REG_CXC_MCIBASIC_REG_OFFSET         0x00024000
#define SEQ_UMAC_TOP_REG_CXC_TOP_REG_CXC_LMH_REG_OFFSET              0x00026000
#define SEQ_UMAC_TOP_REG_CXC_TOP_REG_CXC_SMH_REG_OFFSET              0x00028000
#define SEQ_UMAC_TOP_REG_CXC_TOP_REG_CXC_PMH_REG_OFFSET              0x0002a000
#define SEQ_UMAC_TOP_REG_MAC_TRACER_REG_OFFSET                       0x00030000
#define SEQ_UMAC_TOP_REG_WBM_REG_OFFSET                              0x00034000
#define SEQ_UMAC_TOP_REG_REO_REG_OFFSET                              0x00038000
#define SEQ_UMAC_TOP_REG_TQM_REG_OFFSET                              0x0003c000
#define SEQ_UMAC_TOP_REG_MAC_UMCMN_REG_OFFSET                        0x00040000
#define SEQ_UMAC_TOP_REG_MAC_TCL_REG_OFFSET                          0x00044000
#define SEQ_UMAC_TOP_REG_MAC_CMN_PARSER_REG_OFFSET                   0x00047000
#define SEQ_UMAC_TOP_REG_MAC_CCE_TCL_REG_OFFSET                      0x0004a000


///////////////////////////////////////////////////////////////////////////////////////////////
// Instance Relative Offsets from Block cxc_top_reg
///////////////////////////////////////////////////////////////////////////////////////////////

#define SEQ_CXC_TOP_REG_CXC_BMH_REG_OFFSET                           0x00000000
#define SEQ_CXC_TOP_REG_CXC_LCMH_REG_OFFSET                          0x00002000
#define SEQ_CXC_TOP_REG_CXC_MCIBASIC_REG_OFFSET                      0x00004000
#define SEQ_CXC_TOP_REG_CXC_LMH_REG_OFFSET                           0x00006000
#define SEQ_CXC_TOP_REG_CXC_SMH_REG_OFFSET                           0x00008000
#define SEQ_CXC_TOP_REG_CXC_PMH_REG_OFFSET                           0x0000a000


///////////////////////////////////////////////////////////////////////////////////////////////
// Instance Relative Offsets from Block wmac_top_reg
///////////////////////////////////////////////////////////////////////////////////////////////

#define SEQ_WMAC_TOP_REG_MAC_PDG_REG_OFFSET                          0x00000000
#define SEQ_WMAC_TOP_REG_MAC_TXDMA_REG_OFFSET                        0x00003000
#define SEQ_WMAC_TOP_REG_MAC_RXDMA_REG_OFFSET                        0x00006000
#define SEQ_WMAC_TOP_REG_MAC_MCMN_REG_OFFSET                         0x00009000
#define SEQ_WMAC_TOP_REG_MAC_RXPCU_REG_OFFSET                        0x0000c000
#define SEQ_WMAC_TOP_REG_MAC_TXPCU_REG_OFFSET                        0x0000f000
#define SEQ_WMAC_TOP_REG_MAC_AMPI_REG_OFFSET                         0x00012000
#define SEQ_WMAC_TOP_REG_MAC_RXOLE_REG_OFFSET                        0x00015000
#define SEQ_WMAC_TOP_REG_MAC_RXOLE_PARSER_REG_OFFSET                 0x00018000
#define SEQ_WMAC_TOP_REG_MAC_CCE_REG_OFFSET                          0x0001b000
#define SEQ_WMAC_TOP_REG_MAC_TXOLE_REG_OFFSET                        0x0001e000
#define SEQ_WMAC_TOP_REG_MAC_TXOLE_PARSER_REG_OFFSET                 0x00021000
#define SEQ_WMAC_TOP_REG_MAC_RRI_REG_OFFSET                          0x00024000
#define SEQ_WMAC_TOP_REG_MAC_CRYPTO_REG_OFFSET                       0x00027000
#define SEQ_WMAC_TOP_REG_MAC_HWSCH_REG_OFFSET                        0x0002a000
#define SEQ_WMAC_TOP_REG_MAC_MXI_REG_OFFSET                          0x00030000
#define SEQ_WMAC_TOP_REG_MAC_SFM_REG_OFFSET                          0x00033000
#define SEQ_WMAC_TOP_REG_MAC_RXDMA1_REG_OFFSET                       0x00036000


///////////////////////////////////////////////////////////////////////////////////////////////
// Instance Relative Offsets from Block msip
///////////////////////////////////////////////////////////////////////////////////////////////

#define SEQ_MSIP_RBIST_TX_CH0_OFFSET                                 0x00000000
#define SEQ_MSIP_WL_DAC_CH0_OFFSET                                   0x00000180
#define SEQ_MSIP_WL_DAC_DIG_CORRECTION_CH0_OFFSET                    0x000001c0
#define SEQ_MSIP_WL_DAC_MISC_CH0_OFFSET                              0x000002c0
#define SEQ_MSIP_WL_DAC_BBCLKGEN_CH0_OFFSET                          0x0000033c
#define SEQ_MSIP_WL_ADC_CH0_OFFSET                                   0x00000340
#define SEQ_MSIP_WL_ADC_POSTPROC_I_EVEN_CH0_OFFSET                   0x00000400
#define SEQ_MSIP_WL_ADC_POSTPROC_I_ODD_CH0_OFFSET                    0x00000440
#define SEQ_MSIP_WL_ADC_POSTPROC_Q_EVEN_CH0_OFFSET                   0x00000480
#define SEQ_MSIP_WL_ADC_POSTPROC_Q_ODD_CH0_OFFSET                    0x000004c0
#define SEQ_MSIP_WL_ADC_POSTPROC_RO_CH0_OFFSET                       0x00000500
#define SEQ_MSIP_WL_ADC_BBCLKGEN_CH0_OFFSET                          0x0000059c
#define SEQ_MSIP_RBIST_TX_CH1_OFFSET                                 0x00001000
#define SEQ_MSIP_WL_DAC_CH1_OFFSET                                   0x00001180
#define SEQ_MSIP_WL_DAC_DIG_CORRECTION_CH1_OFFSET                    0x000011c0
#define SEQ_MSIP_WL_DAC_MISC_CH1_OFFSET                              0x000012c0
#define SEQ_MSIP_WL_DAC_BBCLKGEN_CH1_OFFSET                          0x0000133c
#define SEQ_MSIP_WL_ADC_CH1_OFFSET                                   0x00001340
#define SEQ_MSIP_WL_ADC_POSTPROC_I_EVEN_CH1_OFFSET                   0x00001400
#define SEQ_MSIP_WL_ADC_POSTPROC_I_ODD_CH1_OFFSET                    0x00001440
#define SEQ_MSIP_WL_ADC_POSTPROC_Q_EVEN_CH1_OFFSET                   0x00001480
#define SEQ_MSIP_WL_ADC_POSTPROC_Q_ODD_CH1_OFFSET                    0x000014c0
#define SEQ_MSIP_WL_ADC_POSTPROC_RO_CH1_OFFSET                       0x00001500
#define SEQ_MSIP_WL_ADC_BBCLKGEN_CH1_OFFSET                          0x0000159c
#define SEQ_MSIP_RBIST_TX_CH2_OFFSET                                 0x00002000
#define SEQ_MSIP_WL_DAC_CH2_OFFSET                                   0x00002180
#define SEQ_MSIP_WL_DAC_DIG_CORRECTION_CH2_OFFSET                    0x000021c0
#define SEQ_MSIP_WL_DAC_MISC_CH2_OFFSET                              0x000022c0
#define SEQ_MSIP_WL_DAC_BBCLKGEN_CH2_OFFSET                          0x0000233c
#define SEQ_MSIP_WL_ADC_CH2_OFFSET                                   0x00002340
#define SEQ_MSIP_WL_ADC_POSTPROC_I_EVEN_CH2_OFFSET                   0x00002400
#define SEQ_MSIP_WL_ADC_POSTPROC_I_ODD_CH2_OFFSET                    0x00002440
#define SEQ_MSIP_WL_ADC_POSTPROC_Q_EVEN_CH2_OFFSET                   0x00002480
#define SEQ_MSIP_WL_ADC_POSTPROC_Q_ODD_CH2_OFFSET                    0x000024c0
#define SEQ_MSIP_WL_ADC_POSTPROC_RO_CH2_OFFSET                       0x00002500
#define SEQ_MSIP_WL_ADC_BBCLKGEN_CH2_OFFSET                          0x0000259c
#define SEQ_MSIP_RBIST_TX_CH3_OFFSET                                 0x00003000
#define SEQ_MSIP_WL_DAC_CH3_OFFSET                                   0x00003180
#define SEQ_MSIP_WL_DAC_DIG_CORRECTION_CH3_OFFSET                    0x000031c0
#define SEQ_MSIP_WL_DAC_MISC_CH3_OFFSET                              0x000032c0
#define SEQ_MSIP_WL_DAC_BBCLKGEN_CH3_OFFSET                          0x0000333c
#define SEQ_MSIP_WL_ADC_CH3_OFFSET                                   0x00003340
#define SEQ_MSIP_WL_ADC_POSTPROC_I_EVEN_CH3_OFFSET                   0x00003400
#define SEQ_MSIP_WL_ADC_POSTPROC_I_ODD_CH3_OFFSET                    0x00003440
#define SEQ_MSIP_WL_ADC_POSTPROC_Q_EVEN_CH3_OFFSET                   0x00003480
#define SEQ_MSIP_WL_ADC_POSTPROC_Q_ODD_CH3_OFFSET                    0x000034c0
#define SEQ_MSIP_WL_ADC_POSTPROC_RO_CH3_OFFSET                       0x00003500
#define SEQ_MSIP_WL_ADC_BBCLKGEN_CH3_OFFSET                          0x0000359c
#define SEQ_MSIP_MSIP_TMUX_OFFSET                                    0x0000d000
#define SEQ_MSIP_MSIP_OTP_OFFSET                                     0x0000d080
#define SEQ_MSIP_MSIP_LDO_CTRL_OFFSET                                0x0000d0a0
#define SEQ_MSIP_WL_ICIC_OFFSET                                      0x0000d340
#define SEQ_MSIP_WL_ICIC_POSTPROC_I_EVEN_OFFSET                      0x0000d400
#define SEQ_MSIP_WL_ICIC_POSTPROC_I_ODD_OFFSET                       0x0000d440
#define SEQ_MSIP_WL_ICIC_POSTPROC_Q_EVEN_OFFSET                      0x0000d480
#define SEQ_MSIP_WL_ICIC_POSTPROC_Q_ODD_OFFSET                       0x0000d4c0
#define SEQ_MSIP_WL_ICIC_POSTPROC_RO_OFFSET                          0x0000d500
#define SEQ_MSIP_WL_ICIC_BBCLKGEN_OFFSET                             0x0000d59c
#define SEQ_MSIP_MSIP_BIAS_OFFSET                                    0x0000e000
#define SEQ_MSIP_BBPLL_OFFSET                                        0x0000f000
#define SEQ_MSIP_WL_TOP_CLKGEN_OFFSET                                0x0000f800
#define SEQ_MSIP_MSIP_DRM_REG_OFFSET                                 0x0000fc00


///////////////////////////////////////////////////////////////////////////////////////////////
// Instance Relative Offsets from Block wcssdbg
///////////////////////////////////////////////////////////////////////////////////////////////

#define SEQ_WCSSDBG_WCSS_DBG_DAPROM_OFFSET                           0x00000000
#define SEQ_WCSSDBG_CSR_WCSS_DBG_CSR_OFFSET                          0x00001000
#define SEQ_WCSSDBG_TSGEN_CXTSGEN_OFFSET                             0x00002000
#define SEQ_WCSSDBG_CTIDBG_QC_CTI_32T_8CH_OFFSET                     0x00004000
#define SEQ_WCSSDBG_CTINOC_QC_CTI_8T_8CH_OFFSET                      0x00005000
#define SEQ_WCSSDBG_CTIIRQ_QC_CTI_32T_8CH_OFFSET                     0x00006000
#define SEQ_WCSSDBG_WCSS_DBG_TSTMP_INJCTR_OFFSET                     0x00010000
#define SEQ_WCSSDBG_TPDM_OFFSET                                      0x00011000
#define SEQ_WCSSDBG_TPDM_TPDM_ATB64_CMB40_DSB256_CSBE6C04F7_SUB_OFFSET 0x00011280
#define SEQ_WCSSDBG_TPDM_TPDM_ATB64_CMB40_DSB256_CSBE6C04F7_GPR_OFFSET 0x00011000
#define SEQ_WCSSDBG_TPDA_OFFSET                                      0x00012000
#define SEQ_WCSSDBG_CXATBFUNNEL_128W8SP_OFFSET                       0x00013000
#define SEQ_WCSSDBG_TMC_CXTMC_F128W32K_OFFSET                        0x00014000
#define SEQ_WCSSDBG_OUTFUN_CXATBFUNNEL_128W2SP_OFFSET                0x00016000
#define SEQ_WCSSDBG_OUTDMUX_ATB_DEMUX_OFFSET                         0x00018000
#define SEQ_WCSSDBG_TRCCNTRS_OFFSET                                  0x00019000
#define SEQ_WCSSDBG_UNOC_UMAC_NOC_OFFSET                             0x00020000
#define SEQ_WCSSDBG_PHYA_PHYA_DBG_OFFSET                             0x00030000
#define SEQ_WCSSDBG_PHYA_PHYA_DBG_PHYA_NOC_OFFSET                    0x00030000
#define SEQ_WCSSDBG_PHYA_PHYA_DBG_FUN_CXATBFUNNEL_64W8SP_OFFSET      0x00034000
#define SEQ_WCSSDBG_PHYA_PHYA_DBG_CTI_QC_CTI_10T_8CH_OFFSET          0x00035000
#define SEQ_WCSSDBG_PHYA_PHYA_DBG_TRC_PHYTRC_CTRL_OFFSET             0x00036000
#define SEQ_WCSSDBG_PHYA_PHYA_DBG_ITM_OFFSET                         0x00038000
#define SEQ_WCSSDBG_PHYA_PHYA_DBG_DWT_OFFSET                         0x00039000
#define SEQ_WCSSDBG_PHYA_PHYA_DBG_FPB_OFFSET                         0x0003a000
#define SEQ_WCSSDBG_PHYA_PHYA_DBG_SCS_OFFSET                         0x0003b000
#define SEQ_WCSSDBG_PHYA_PHYA_DBG_M3_ETM_OFFSET                      0x0003c000
#define SEQ_WCSSDBG_PHYA_PHYA_DBG_M3CTI_QC_CTI_8T_8CH_OFFSET         0x0003d000
#define SEQ_WCSSDBG_PHYA_PHYA_DBG_CPU0_M3_AHB_AP_OFFSET              0x0003e000
#define SEQ_WCSSDBG_BUS_TIMEOUT_OFFSET                               0x00071000


///////////////////////////////////////////////////////////////////////////////////////////////
// Instance Relative Offsets from Block tpdm_atb64_cmb40_dsb256_csbe6c04f7
///////////////////////////////////////////////////////////////////////////////////////////////

#define SEQ_TPDM_ATB64_CMB40_DSB256_CSBE6C04F7_TPDM_ATB64_CMB40_DSB256_CSBE6C04F7_SUB_OFFSET 0x00000280
#define SEQ_TPDM_ATB64_CMB40_DSB256_CSBE6C04F7_TPDM_ATB64_CMB40_DSB256_CSBE6C04F7_GPR_OFFSET 0x00000000


///////////////////////////////////////////////////////////////////////////////////////////////
// Instance Relative Offsets from Block phya_dbg
///////////////////////////////////////////////////////////////////////////////////////////////

#define SEQ_PHYA_DBG_PHYA_NOC_OFFSET                                 0x00000000
#define SEQ_PHYA_DBG_FUN_CXATBFUNNEL_64W8SP_OFFSET                   0x00004000
#define SEQ_PHYA_DBG_CTI_QC_CTI_10T_8CH_OFFSET                       0x00005000
#define SEQ_PHYA_DBG_TRC_PHYTRC_CTRL_OFFSET                          0x00006000
#define SEQ_PHYA_DBG_ITM_OFFSET                                      0x00008000
#define SEQ_PHYA_DBG_DWT_OFFSET                                      0x00009000
#define SEQ_PHYA_DBG_FPB_OFFSET                                      0x0000a000
#define SEQ_PHYA_DBG_SCS_OFFSET                                      0x0000b000
#define SEQ_PHYA_DBG_M3_ETM_OFFSET                                   0x0000c000
#define SEQ_PHYA_DBG_M3CTI_QC_CTI_8T_8CH_OFFSET                      0x0000d000
#define SEQ_PHYA_DBG_CPU0_M3_AHB_AP_OFFSET                           0x0000e000


///////////////////////////////////////////////////////////////////////////////////////////////
// Instance Relative Offsets from Block qdsp6v67ss_wlan_pine
///////////////////////////////////////////////////////////////////////////////////////////////

#define SEQ_QDSP6V67SS_WLAN_PINE_QDSP6V67SS_OFFSET                   0x00000000
#define SEQ_QDSP6V67SS_WLAN_PINE_QDSP6V67SS_QDSP6V67SS_PUBLIC_OFFSET 0x00000000
#define SEQ_QDSP6V67SS_WLAN_PINE_QDSP6V67SS_QDSP6V67SS_PUBLIC_QDSP6V67SS_PUB_OFFSET 0x00000000
#define SEQ_QDSP6V67SS_WLAN_PINE_QDSP6V67SS_QDSP6V67SS_PRIVATE_OFFSET 0x00080000
#define SEQ_QDSP6V67SS_WLAN_PINE_QDSP6V67SS_QDSP6V67SS_PRIVATE_QDSP6V67SS_CSR_OFFSET 0x00080000
#define SEQ_QDSP6V67SS_WLAN_PINE_QDSP6V67SS_QDSP6V67SS_PRIVATE_QDSP6V67SS_L2VIC_OFFSET 0x00090000
#define SEQ_QDSP6V67SS_WLAN_PINE_QDSP6V67SS_QDSP6V67SS_PRIVATE_QDSP6SS_QTMR_AC_OFFSET 0x000a0000
#define SEQ_QDSP6V67SS_WLAN_PINE_QDSP6V67SS_QDSP6V67SS_PRIVATE_QTMR_F0_OFFSET 0x000a1000
#define SEQ_QDSP6V67SS_WLAN_PINE_QDSP6V67SS_QDSP6V67SS_PRIVATE_QTMR_F1_OFFSET 0x000a2000
#define SEQ_QDSP6V67SS_WLAN_PINE_QDSP6V67SS_QDSP6V67SS_PRIVATE_QTMR_F2_OFFSET 0x000a3000
#define SEQ_QDSP6V67SS_WLAN_PINE_QDSP6V67SS_QDSP6V67SS_PRIVATE_QDSP6V67SS_RSCC_OFFSET 0x000b0000
#define SEQ_QDSP6V67SS_WLAN_PINE_QDSP6V67SS_QDSP6V67SS_PRIVATE_QDSP6V67SS_RSCC_RSCC_RSC_OFFSET 0x000b0000


///////////////////////////////////////////////////////////////////////////////////////////////
// Instance Relative Offsets from Block qdsp6v67ss
///////////////////////////////////////////////////////////////////////////////////////////////

#define SEQ_QDSP6V67SS_QDSP6V67SS_PUBLIC_OFFSET                      0x00000000
#define SEQ_QDSP6V67SS_QDSP6V67SS_PUBLIC_QDSP6V67SS_PUB_OFFSET       0x00000000
#define SEQ_QDSP6V67SS_QDSP6V67SS_PRIVATE_OFFSET                     0x00080000
#define SEQ_QDSP6V67SS_QDSP6V67SS_PRIVATE_QDSP6V67SS_CSR_OFFSET      0x00080000
#define SEQ_QDSP6V67SS_QDSP6V67SS_PRIVATE_QDSP6V67SS_L2VIC_OFFSET    0x00090000
#define SEQ_QDSP6V67SS_QDSP6V67SS_PRIVATE_QDSP6SS_QTMR_AC_OFFSET     0x000a0000
#define SEQ_QDSP6V67SS_QDSP6V67SS_PRIVATE_QTMR_F0_OFFSET             0x000a1000
#define SEQ_QDSP6V67SS_QDSP6V67SS_PRIVATE_QTMR_F1_OFFSET             0x000a2000
#define SEQ_QDSP6V67SS_QDSP6V67SS_PRIVATE_QTMR_F2_OFFSET             0x000a3000
#define SEQ_QDSP6V67SS_QDSP6V67SS_PRIVATE_QDSP6V67SS_RSCC_OFFSET     0x000b0000
#define SEQ_QDSP6V67SS_QDSP6V67SS_PRIVATE_QDSP6V67SS_RSCC_RSCC_RSC_OFFSET 0x000b0000


///////////////////////////////////////////////////////////////////////////////////////////////
// Instance Relative Offsets from Block qdsp6v67ss_public
///////////////////////////////////////////////////////////////////////////////////////////////

#define SEQ_QDSP6V67SS_PUBLIC_QDSP6V67SS_PUB_OFFSET                  0x00000000


///////////////////////////////////////////////////////////////////////////////////////////////
// Instance Relative Offsets from Block qdsp6v67ss_private
///////////////////////////////////////////////////////////////////////////////////////////////

#define SEQ_QDSP6V67SS_PRIVATE_QDSP6V67SS_CSR_OFFSET                 0x00000000
#define SEQ_QDSP6V67SS_PRIVATE_QDSP6V67SS_L2VIC_OFFSET               0x00010000
#define SEQ_QDSP6V67SS_PRIVATE_QDSP6SS_QTMR_AC_OFFSET                0x00020000
#define SEQ_QDSP6V67SS_PRIVATE_QTMR_F0_OFFSET                        0x00021000
#define SEQ_QDSP6V67SS_PRIVATE_QTMR_F1_OFFSET                        0x00022000
#define SEQ_QDSP6V67SS_PRIVATE_QTMR_F2_OFFSET                        0x00023000
#define SEQ_QDSP6V67SS_PRIVATE_QDSP6V67SS_RSCC_OFFSET                0x00030000
#define SEQ_QDSP6V67SS_PRIVATE_QDSP6V67SS_RSCC_RSCC_RSC_OFFSET       0x00030000


///////////////////////////////////////////////////////////////////////////////////////////////
// Instance Relative Offsets from Block q6ss_rscc
///////////////////////////////////////////////////////////////////////////////////////////////

#define SEQ_Q6SS_RSCC_RSCC_RSC_OFFSET                                0x00000000


#endif

