LINUXINCLUDE    += -I$(EVA_ROOT)/include \
                   -I$(EVA_ROOT)/include/uapi \
				   -I$(EVA_ROOT)/include/uapi/eva

#srctree is /kernel_platform/common/

ccflags-y += -I$(srctree)/techpack/eva/msm/eva/ \
    -I$(srctree)/drivers/media/platform/msm/synx/

# add flag to compile mmrm actual implementatio instead of stub version.
# to follow up with mmrm team if techpack users need to define this for long term?
KBUILD_CPPFLAGS += -DCONFIG_MSM_MMRM

# ported from Android.mk
$(info within KBUILD file KBUILD_EXTRA_SYMBOLS = $(KBUILD_EXTRA_SYMBOLS))

msm-eva-objs := eva/cvp.o \
        eva/msm_cvp_ioctl.o \
        eva/msm_cvp_platform.o \
        eva/msm_cvp_common.o \
        eva/msm_cvp_core.o \
        eva/msm_cvp.o \
        eva/msm_smem.o \
        eva/msm_cvp_debug.o \
        eva/msm_cvp_res_parse.o \
        eva/cvp_dump.o \
        eva/cvp_hfi.o \
        eva/hfi_response_handler.o \
        eva/hfi_packetization.o \
        eva/cvp_core_hfi.o \
        eva/msm_cvp_clocks.o\
        eva/msm_cvp_dsp.o \
        eva/msm_cvp_buf.o \
        eva/msm_cvp_synx.o \
		eva/cvp_fw_load.o
obj-m += msm-eva.o

