ifdef CONFIG_MSM_MMRM
LINUXINCLUDE += -I$(MMRM_ROOT)/driver/src

obj-m += msm-mmrm.o
msm-mmrm-objs := src/msm_mmrm.o \
				src/mmrm_internal.o \
				src/mmrm_res_parse.o \
				src/mmrm_debug.o \
				src/mmrm_clk_rsrc_mgr_sw.o \
				src/mmrm_clk_rsrc_mgr.o
endif
