ccflags-y += -I$(srctree)/techpack/mmrm/driver/src/

msm-mmrm-objs := src/msm_mmrm.o \
				src/mmrm_internal.o \
				src/mmrm_res_parse.o \
				src/mmrm_debug.o \
				src/mmrm_clk_rsrc_mgr_sw.o \
				src/mmrm_clk_rsrc_mgr.o

obj-$(CONFIG_MSM_MMRM) := msm-mmrm.o
