/*
 * Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#define ANI_OS_TYPE_ANDROID 6
#define ATH_SUPPORT_WRAP 0
#define CHECK_REG_PHYMODE 1
#define CONFIG_CHAN_FREQ_API 1
#define CONFIG_CHAN_NUM_API 1
#define CONFIG_FW_LOGS_BASED_ON_INI 1
#define CONN_MGR_ADV_FEATURE 1
#define CRYPTO_SET_KEY_CONVERGED 1
#define DP_CON_MON 1
#define DP_FLOW_CTL 1
#define DP_INTR_POLL_BOTH 1
#define DP_INVALID_PEER_ASSERT 1
#define DP_MOB_DEFS 1
#define DP_PEER_EXTENDED_API 1
#define DP_POWER_SAVE 1
#define DP_PRINT_ENABLE 0
#define DP_PRINT_NO_CONSOLE 1
#define FEATURE_NBUFF_REPLENISH_TIMER 1
#define LOG_DEL_OBJ_DESTROY_DURATION_SEC 4
#define LOG_DEL_OBJ_TIMEOUT_VALUE_MSEC 4000
#define MWS_COEX 1
#define PCIE_REG_WINDOW_LOCAL_NO_CACHE 1
#define PEER_CACHE_RX_PKTS 1
#define QCA_HOST2FW_RXBUF_RING 1
#define QCA_HT_2040_COEX 1
#define QCA_SUPPORT_TXRX_LOCAL_PEER_ID 1
#define SCHEDULER_CORE_MAX_MESSAGES 1000
#define SERIALIZE_VDEV_RESP 1
#define TGT_IF_VDEV_MGR_CONV 1
#define WLAN_CONV_CRYPTO_SUPPORTED 1
#define WLAN_CRYPTO_CCMP_OS_DERIVATIVE 1
#define WLAN_CRYPTO_FILS_OS_DERIVATIVE 1
#define WLAN_CRYPTO_GCMP_OS_DERIVATIVE 1
#define WLAN_CRYPTO_GCM_OS_DERIVATIVE 1
#define WLAN_CRYPTO_OMAC1_OS_DERIVATIVE 1
#define WLAN_CRYPTO_TKIP_OS_DERIVATIVE 1
#define WLAN_CRYPTO_WAPI_OS_DERIVATIVE 1
#define WLAN_CRYPTO_WEP_OS_DERIVATIVE 1
#define WLAN_FEATURE_INTERFACE_MGR 1
#define WLAN_FEATURE_P2P 1
#define WLAN_FEATURE_WFD 1
#define WLAN_OBJMGR_RATELIMIT_THRESH 0
#define WLAN_SCHED_REDUCTION_LIMIT 0
#define WMI_MULTI_MAC_SVC 1
#define __linux__ 1
